[package]
name = "city_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.16.0"
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.93"
